version: "3"

services:
    client:
        image: ubuntu
        volumes:
            - ../:/workspace
        command: sleep infinity
        networks:
            net-10.9.0.0:
                ipv4_address: 10.9.0.100
    web-server:
        build: ./image_www
        image: seed-image-www-pki
        container_name: www-10.9.0.80
        tty: true
        volumes:
            - ./volumes:/volumes

        networks:
            net-10.9.0.0:
                ipv4_address: 10.9.0.80

networks:
    net-10.9.0.0:
        name: net-10.9.0.0
        ipam:
            config:
                - subnet: 10.9.0.0/24
